language: node_js
node_js:
  - 10

jobs:
  include:
    - stage: "Tests"
      if: branch = master OR branch = release
      script: npm start

    # Docker deployment only happen for "master" and "release" branches.
    - stage: "Docker-Deployment"
      script: node index2.js
