language: node_js
node_js:
  - 10

jobs:
  include:
    - stage: "Tests"
      if: env(TRAVIS_BRANCH) = task1
      script: npm start

    # Docker deployment only happen for "master" and "release" branches.
    - stage: "Docker-Deployment"
      script: node index2.js
