language: node_js
node_js:
  - 10

jobs:
  include:
    - stage: "Tests"
      script: npm start

    - stage: "Failssssssss"
      script: npm test

    # Docker deployment only happen for "master" and "release" branches.
    - stage: "Docker-Deployment"
      script: node index2.js
